version: '3.8'
services:
  db:
    image: postgres:13.7-alpine
    container_name: shareit_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  server:
    build: ./server
    container_name: shareit_server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - DB_NAME=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
  gateway:
    build: ./gateway
    container_name: shareit_gateway
    ports:
      - "8081:8081"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://localhost:9090


