logging:
  level:
    ru:
      practicum:
        shareit: debug
server:
  port: 9090
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:H2DB
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: false
  sql:
    init:
      mode: always
