logging:
  level:
    ru:
      practicum:
        shareit: debug
server:
  port: 9123
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shareit
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: false
  sql:
    init:
      mode: always
